### ISSUE TITLE
Aligning the graphs creates overlaps in the labels.

### ISSUE THREAD

**Issue by Gurnek** [matplotlib/grid-strategy#26]
When specifying the justification of a GraphStrategy, the spacing is no spread out far enough and it overlaps with other graphs.
![left](https://user-images.githubusercontent.com/28551755/53291077-37e48280-3773-11e9-8cd8-741756501c7e.png)
![right](https://user-images.githubusercontent.com/28551755/53291079-3ca93680-3773-11e9-8aa7-b8078825dc07.png)

**Comment by tacaswell** [comment]
Using constrained layout may help here.

**Comment by pganssle** [comment]
Fixed in #29, thanks @tacaswell!
