### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by pganssle** [matplotlib/grid-strategy#3]
We should have `tests/test_strategies.py`, using `pytest` with parametrized tests.

**Comment by Gurnek** [comment]
I have the most basic of tests. We should add a way of returning an error when bad inputs are passed into the get_grid functions.

**Comment by pganssle** [comment]
@Gurnek Generally speaking I prefer to raise exceptions rather than returning errors, but yes we should check for bad inputs and add tests to make sure that the exceptions we're expecting are raised!

**Comment by pganssle** [comment]
Code coverage is now 100%.
